name: native_designs
description: A new Flutter project.


version: 1.0.0+4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  cloud_firestore: ^3.1.10
  firebase_core: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/


